module.exports = [
    {
        id: 1,
        rav_id: 84979,
        name: 'Silkpaca',
        yarn_company: 'Malabrigo Yarn',
        yarn_weight: 'Lace',
        yardage: 420,
        grams: 100,
        machine_washable: false,
        texture: 'silk',
        photo: "https://images4-f.ravelrycache.com/uploads/LorenWeiss/675018551/upload_small_best_fit",
        permalink: 'malabrigo-yarn-silkpaca',
    },
    {
        id: 2,
        rav_id: 52345,
        name: 'Tough Love Sock',
        yarn_company: 'SweetGeorgia Yarns',
        yarn_weight: 'Fingering',
        yardage: 425,
        grams: 100,
        machine_washable: true,
        texture: 'plied',
        photo: "https://images4-g.ravelrycache.com/uploads/sweetgeorgia/431920520/Tough_Love_Sock-780_small_best_fit.jpg",
        permalink: 'sweetgeorgia-yarns-tough-love-sock',
    },
    {
        id: 3,
        rav_id: 54983,
        name: 'Pashmina',
        yarn_company: 'madelinetosh',
        yarn_weight: 'Sport',
        yardage: 360,
        grams: 100,
        machine_washable: false,
        texture: 'single ply',
        photo: "https://images4-g.ravelrycache.com/uploads/madelinetosh/539192904/Screen_Shot_2018-08-06_at_12.49.20_PM_small_best_fit.png",
        permalink: 'madelinetosh-pashmina',
    },
    {
        id: 4,
        rav_id: 6580,
        name: 'Sea Silk',
        yarn_company: 'Handmaiden Fine Yarn',
        yarn_weight: 'Fingering',
        yardage: 437,
        grams: 100,
        machine_washable: false,
        texture: 'silk',
        photo: "https://images4-f.ravelrycache.com/uploads/HandmaidenYarns/434810857/seasilk-frozenocean_small_best_fit.jpg",
        permalink: 'hand-maiden-fine-yarn-sea-silk',
    },
]